FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04
ARG PYTHON_VERSION=3.10
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    python${PYTHON_VERSION} python3-pip git && \
    rm -rf /var/lib/apt/lists/*
RUN python3 -m pip install --upgrade pip
WORKDIR /workspace
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY . .
RUN pip install -e .
CMD ["/bin/bash"]
