# Model parameters
model:
  perception:
    input_channels: 1
    base_channels: 64
    embedding_dim: 128
  reconstruction:
    input_channels: 2 # z_t + x_fbp
    base_channels: 64
    conditioning_dim: 256 # time_emb + dose_emb

# Training parameters
training:
  batch_size: 8
  num_epochs: 100
  learning_rate: 1e-4
  weight_decay: 0.01
  max_steps: 20
  min_steps: 4
  eta_schedule: [0.1, 0.08, 0.06, 0.05, 0.04, 0.03, 0.02, 0.01] # Example schedule

# Physics parameters
physics:
  geometry:
    angles: 720
    det_width: 1000
    pixel_size: 0.5
  fbp_filter: "hann"

# Data parameters
data:
  hu_range: [-1024, 3072]
  patch_size: 384
  num_workers: 4
